#
# Pre-commit hooks
#
default_stages: [pre-commit, manual]
repos:
- repo: local
  hooks:
    - id: format_license_lgpl
      name: format_license_lgpl 
      entry: reuse annotate --copyright 'All contributors' --license 'LGPL-2.1-or-later' --merge-copyrights --copyright-style 'spdx'
      types_or: ["c++", "c", "qml"]
      files: ^(multimedia/|multimedia_test_helper/|upnpav/|upnpav_test_helper)
      language: python
      additional_dependencies: ["reuse"]

    - id: format_license_gpl
      name: format_license_gpl 
      entry: reuse annotate --copyright 'All contributors' --license 'GPL-2.0-or-later' --merge-copyrights --copyright-style 'spdx'
      types_or: ["c++", "c", "qml"]
      files: ^(shell/|providers/)
      language: python
      additional_dependencies: ["reuse"]

    - id: check_license
      name: check_license
      entry: reuse lint
      language: python
      pass_filenames: false
      additional_dependencies: ["reuse"]

    - id: format_qml
      name: format_qml
      entry: qmlformat6 -i -l native -w 4
      types_or: ["qml"]
      language: system
