var annotated_dup =
[
    [ "PluginCore", null, [
      [ "MultimediaPlugin", "classPluginCore_1_1MultimediaPlugin.html", "classPluginCore_1_1MultimediaPlugin" ],
      [ "PluginVersion", "structPluginCore_1_1PluginVersion.html", "structPluginCore_1_1PluginVersion" ],
      [ "MultimediaPluginPrivate", "classPluginCore_1_1MultimediaPluginPrivate.html", "classPluginCore_1_1MultimediaPluginPrivate" ]
    ] ],
    [ "UPnPAV", null, [
      [ "BrowseResult", "classUPnPAV_1_1BrowseResult.html", "classUPnPAV_1_1BrowseResult" ],
      [ "CurrentConnectionIdsResult", "classUPnPAV_1_1CurrentConnectionIdsResult.html", "classUPnPAV_1_1CurrentConnectionIdsResult" ],
      [ "ConnectionInfo", "structUPnPAV_1_1ConnectionInfo.html", "structUPnPAV_1_1ConnectionInfo" ],
      [ "CurrentConnectionInfoResult", "classUPnPAV_1_1CurrentConnectionInfoResult.html", "classUPnPAV_1_1CurrentConnectionInfoResult" ],
      [ "DescriptionFetcherBackend", "classUPnPAV_1_1DescriptionFetcherBackend.html", "classUPnPAV_1_1DescriptionFetcherBackend" ],
      [ "HttpDescriptionFetcherBackend", "classUPnPAV_1_1HttpDescriptionFetcherBackend.html", "classUPnPAV_1_1HttpDescriptionFetcherBackend" ],
      [ "DeviceDescription", "classUPnPAV_1_1DeviceDescription.html", "classUPnPAV_1_1DeviceDescription" ],
      [ "GetDeviceCapabilitiesResponse", "classUPnPAV_1_1GetDeviceCapabilitiesResponse.html", "classUPnPAV_1_1GetDeviceCapabilitiesResponse" ],
      [ "GetDeviceCapabilitiesResponseData", "structUPnPAV_1_1GetDeviceCapabilitiesResponseData.html", "structUPnPAV_1_1GetDeviceCapabilitiesResponseData" ],
      [ "GetMediaInfoResponse", "classUPnPAV_1_1GetMediaInfoResponse.html", "classUPnPAV_1_1GetMediaInfoResponse" ],
      [ "GetMediaInfoResponseData", "structUPnPAV_1_1GetMediaInfoResponseData.html", "structUPnPAV_1_1GetMediaInfoResponseData" ],
      [ "GetPositionInfoResponse", "classUPnPAV_1_1GetPositionInfoResponse.html", "classUPnPAV_1_1GetPositionInfoResponse" ],
      [ "GetPositionInfoResponseData", "structUPnPAV_1_1GetPositionInfoResponseData.html", "structUPnPAV_1_1GetPositionInfoResponseData" ],
      [ "GetTransportInfoResponse", "classUPnPAV_1_1GetTransportInfoResponse.html", "classUPnPAV_1_1GetTransportInfoResponse" ],
      [ "GetTransportInfoResponseData", "structUPnPAV_1_1GetTransportInfoResponseData.html", "structUPnPAV_1_1GetTransportInfoResponseData" ],
      [ "GetTransportSettingsResponse", "classUPnPAV_1_1GetTransportSettingsResponse.html", "classUPnPAV_1_1GetTransportSettingsResponse" ],
      [ "GetTransportSettingsResponseData", "structUPnPAV_1_1GetTransportSettingsResponseData.html", "structUPnPAV_1_1GetTransportSettingsResponseData" ],
      [ "HttpSoapMessageTransmitter", "classUPnPAV_1_1HttpSoapMessageTransmitter.html", "classUPnPAV_1_1HttpSoapMessageTransmitter" ],
      [ "IconDescription", "classUPnPAV_1_1IconDescription.html", "classUPnPAV_1_1IconDescription" ],
      [ "InvalidDeviceDescription", "classUPnPAV_1_1InvalidDeviceDescription.html", "classUPnPAV_1_1InvalidDeviceDescription" ],
      [ "IServiceProvider", "classUPnPAV_1_1IServiceProvider.html", "classUPnPAV_1_1IServiceProvider" ],
      [ "IServiceProviderFactory", "classUPnPAV_1_1IServiceProviderFactory.html", "classUPnPAV_1_1IServiceProviderFactory" ],
      [ "MediaDevice", "classUPnPAV_1_1MediaDevice.html", "classUPnPAV_1_1MediaDevice" ],
      [ "MediaServer", "classUPnPAV_1_1MediaServer.html", "classUPnPAV_1_1MediaServer" ],
      [ "MediaServerFactory", "classUPnPAV_1_1MediaServerFactory.html", "classUPnPAV_1_1MediaServerFactory" ],
      [ "MediaServerObject", "classUPnPAV_1_1MediaServerObject.html", "classUPnPAV_1_1MediaServerObject" ],
      [ "PendingSoapCall", "classUPnPAV_1_1PendingSoapCall.html", "classUPnPAV_1_1PendingSoapCall" ],
      [ "AvTransportServiceValidator", "classUPnPAV_1_1AvTransportServiceValidator.html", "classUPnPAV_1_1AvTransportServiceValidator" ],
      [ "BaseValidator", "classUPnPAV_1_1BaseValidator.html", "classUPnPAV_1_1BaseValidator" ],
      [ "ConnectionManagerServiceValidator", "classUPnPAV_1_1ConnectionManagerServiceValidator.html", "classUPnPAV_1_1ConnectionManagerServiceValidator" ],
      [ "ContentDirectoryServiceValidator", "classUPnPAV_1_1ContentDirectoryServiceValidator.html", "classUPnPAV_1_1ContentDirectoryServiceValidator" ],
      [ "DescriptionFetcher", "classUPnPAV_1_1DescriptionFetcher.html", "classUPnPAV_1_1DescriptionFetcher" ],
      [ "DeviceDescriptionParser", "classUPnPAV_1_1DeviceDescriptionParser.html", "classUPnPAV_1_1DeviceDescriptionParser" ],
      [ "ErrorResult", "classUPnPAV_1_1ErrorResult.html", "classUPnPAV_1_1ErrorResult" ],
      [ "HttpSoapCall", "classUPnPAV_1_1HttpSoapCall.html", "classUPnPAV_1_1HttpSoapCall" ],
      [ "MediaDevicePrivate", "classUPnPAV_1_1MediaDevicePrivate.html", "classUPnPAV_1_1MediaDevicePrivate" ],
      [ "MediaServerPrivate", "classUPnPAV_1_1MediaServerPrivate.html", "classUPnPAV_1_1MediaServerPrivate" ],
      [ "ResponseReader", "classUPnPAV_1_1ResponseReader.html", "classUPnPAV_1_1ResponseReader" ],
      [ "ScpdActionListValidator", "classUPnPAV_1_1ScpdActionListValidator.html", "classUPnPAV_1_1ScpdActionListValidator" ],
      [ "ScpdStateVariableValidator", "classUPnPAV_1_1ScpdStateVariableValidator.html", "classUPnPAV_1_1ScpdStateVariableValidator" ],
      [ "ServiceControlPointDefinitionParser", "classUPnPAV_1_1ServiceControlPointDefinitionParser.html", "classUPnPAV_1_1ServiceControlPointDefinitionParser" ],
      [ "ServiceDescriptionValidator", "classUPnPAV_1_1ServiceDescriptionValidator.html", "classUPnPAV_1_1ServiceDescriptionValidator" ],
      [ "ServiceDiscovery", "classUPnPAV_1_1ServiceDiscovery.html", "classUPnPAV_1_1ServiceDiscovery" ],
      [ "ServiceDiscoveryPackage", "classUPnPAV_1_1ServiceDiscoveryPackage.html", "classUPnPAV_1_1ServiceDiscoveryPackage" ],
      [ "PackageParseError", "classUPnPAV_1_1PackageParseError.html", "classUPnPAV_1_1PackageParseError" ],
      [ "ServiceValidatorBase", "classUPnPAV_1_1ServiceValidatorBase.html", "classUPnPAV_1_1ServiceValidatorBase" ],
      [ "Argument", "structUPnPAV_1_1Argument.html", "structUPnPAV_1_1Argument" ],
      [ "SoapMessageGenerator", "classUPnPAV_1_1SoapMessageGenerator.html", "classUPnPAV_1_1SoapMessageGenerator" ],
      [ "Protocol", "structUPnPAV_1_1Protocol.html", "structUPnPAV_1_1Protocol" ],
      [ "ProtocolInfoResult", "classUPnPAV_1_1ProtocolInfoResult.html", "classUPnPAV_1_1ProtocolInfoResult" ],
      [ "SCPDAction", "classUPnPAV_1_1SCPDAction.html", "classUPnPAV_1_1SCPDAction" ],
      [ "SCPDActionData", "structUPnPAV_1_1SCPDActionData.html", "structUPnPAV_1_1SCPDActionData" ],
      [ "SCPDArgument", "classUPnPAV_1_1SCPDArgument.html", "classUPnPAV_1_1SCPDArgument" ],
      [ "SCPDArgumentData", "structUPnPAV_1_1SCPDArgumentData.html", "structUPnPAV_1_1SCPDArgumentData" ],
      [ "SCPDStateVariable", "classUPnPAV_1_1SCPDStateVariable.html", "classUPnPAV_1_1SCPDStateVariable" ],
      [ "SCPDStateVariableData", "structUPnPAV_1_1SCPDStateVariableData.html", "structUPnPAV_1_1SCPDStateVariableData" ],
      [ "ServiceControlPointDefinition", "classUPnPAV_1_1ServiceControlPointDefinition.html", "classUPnPAV_1_1ServiceControlPointDefinition" ],
      [ "ServiceControlPointDefinitionData", "structUPnPAV_1_1ServiceControlPointDefinitionData.html", "structUPnPAV_1_1ServiceControlPointDefinitionData" ],
      [ "ServiceDescription", "classUPnPAV_1_1ServiceDescription.html", "classUPnPAV_1_1ServiceDescription" ],
      [ "ServiceDescriptionData", "structUPnPAV_1_1ServiceDescriptionData.html", "structUPnPAV_1_1ServiceDescriptionData" ],
      [ "ServiceDiscoveryBackend", "classUPnPAV_1_1ServiceDiscoveryBackend.html", "classUPnPAV_1_1ServiceDiscoveryBackend" ],
      [ "UdpServiceDiscoveryBackend", "classUPnPAV_1_1UdpServiceDiscoveryBackend.html", "classUPnPAV_1_1UdpServiceDiscoveryBackend" ],
      [ "ServiceProvider", "classUPnPAV_1_1ServiceProvider.html", "classUPnPAV_1_1ServiceProvider" ],
      [ "ServiceProviderFactory", "classUPnPAV_1_1ServiceProviderFactory.html", "classUPnPAV_1_1ServiceProviderFactory" ],
      [ "ServiceProviderError", "classUPnPAV_1_1ServiceProviderError.html", "classUPnPAV_1_1ServiceProviderError" ],
      [ "SoapCall", "classUPnPAV_1_1SoapCall.html", "classUPnPAV_1_1SoapCall" ],
      [ "SoapMessageTransmitter", "classUPnPAV_1_1SoapMessageTransmitter.html", "classUPnPAV_1_1SoapMessageTransmitter" ]
    ] ],
    [ "ParsingError", "classParsingError.html", "classParsingError" ]
];