@startuml inline_umlgraph_1.png
node "Blabby" {
    node "Core" {
        component UPnPAV as upnpav{
            [ServiceDiscovery]
            [MediaDevice]
        }

        component MultiMedia as media {
            [ProviderPlugin]
            [MultiMedia]
            [Renderer]

            [Renderer] --> [MediaDevice]
            [Renderer] --> [ServiceDiscovery]

            [MultiMedia] --> [ProviderPlugin]
        }

        component Shell as shell
        shell --> [MultiMedia]
        shell --> [Renderer]
    }
}
@enduml
