name: "llhttp-build"
description: "Builds the nodejs-llhttp library"
inputs:
  version:
    description: "Which version of llhttp shall be build."
    required: false
    default: v9.1.3
  os:
    description: 'Runner OS'
    required: false
    default: 'default'
runs:
  using: "composite"
  steps:
    - name: "Builds and Installs nodejs-llhttp"
      if: (inputs.os == 'ubuntu-latest') || (inputs.os == 'ubuntu-22.04') || (inputs.os == 'default')
      shell: bash
      run: |
          echo "Downloading"
          wget https://github.com/nodejs/llhttp/archive/refs/tags/release/${{ inputs.version }}.tar.gz
          echo "Unpacking"
          tar xf ${{ inputs.version }}.tar.gz
          echo "Switching directory"
          echo "Build"
          mkdir build
          cmake -B build -S llhttp-release-${{ inputs.version }} -DCMAKE_BUILD_TYPE=Release \
          -DBUILD_SHARED_LIBS=ON \
          -DCMAKE_INSTALL_PREFIX=/usr
          sudo cmake --build build --target install
