name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  setup:
    
    runs-on: ubuntu-latest
    
    steps:
    - name: Install Qt
      uses: jurplel/install-qt-action@v2.6.2
      with:
        version: '5.13.2'
    
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: configure
      run: cmake ..
    - name: make
      run: make

