name: Blabby CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Install Qt
      uses: jurplel/install-qt-action@v2.6.2
      with:
        version: '5.13.2'
    - name: checkout
      uses: actions/checkout@v2
    - name: configure
      run: mkdir -p build && cd build
      run: cmake -DENABLE_TEST=ON ..
    - name: make
      run: make -j8
    - name: tests
      run: ctest

