name: Blabby CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Install Qt
      uses: jurplel/install-qt-action@v2.6.2
      with:
        version: '5.13.2'
    - name: checkout
      uses: actions/checkout@v2
    - name: configure
      run: cmake blabby
    - name: make
      run: make

