# SPDX-FileCopyrightText: 2021 Florian Weßel <florianwessel@gmx.net>
#
# SPDX-License-Identifier: GPL-2.0-or-later

name: Blabby CI

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-26.04
    env:
      CC: gcc-15
      CXX: g++-15
    steps:
    - name: Install Qt
      uses: jurplel/install-qt-action@v3
      with:
        version: '6.5.*'
        cache: 'true'
    - name: Install Dependencies
      run: |
        sudo apt update && sudo apt install -y doxygen
    - name: checkout
      uses: actions/checkout@v4
    - name: Build and Install nodejs-llhttp
      uses: ./.github/actions/llhttp-build
    - name: build and test
      run: |
        cmake --preset github-ci-debug
        cmake --build --preset github-ci-debug -- -j$(nproc)
        ctest --preset github-test --output-on-failure
      env:
        QT_QPA_PLATFORM: offscreen
