# SPDX-FileCopyrightText: 2021 Florian Weßel <florianwessel@gmx.net>
#
# SPDX-License-Identifier: GPL-2.0-or-later
name: Blabby Deploy Docs

on:
  push:
    branches: [ main ]
permissions:
  contents: write

jobs:
  deploy-docs:
    runs-on: ubuntu-latest
    steps:
    - name: Install Qt
      uses: jurplel/install-qt-action@v3
      with:
        version: '6.5.*'
        cache: 'true'
    - name: Install Dependencies
      run: |
        sudo apt update && sudo apt install doxygen plantuml
    - name: checkout
      uses: actions/checkout@v4
    - name: build docs
      run: |
        cmake --preset github-ci-debug
        cmake --build --preset github-ci-debug --target docs
      env:
        PLANTUML_JAR: "/usr/share/plantuml/plantuml.jar"
    - name: deploy docs
      uses: JamesIves/github-pages-deploy-action@v4
      with:
          folder: build-github-ci-debug/doc/html
