# SPDX-FileCopyrightText: 2021 Florian Weßel <florianwessel@gmx.net>
#
# SPDX-License-Identifier: GPL-2.0-or-later
name: Blabby Deploy Docs

on:
  push:
    branches: [ main ]
permissions:
  contents: write

jobs:
  deploy-docs:
    runs-on: ubuntu-latest
    steps:
    - name: Install Qt
      uses: jurplel/install-qt-action@v3
      with:
        version: '6.5.*'
        cache: 'true'
    - name: Install Packages
      run: sudo apt-get update && sudo apt-get install graphviz
    - name: Download and Install Doxygen
      run: |
        wget https://www.doxygen.nl/files/doxygen-1.9.8.linux.bin.tar.gz
        tar xf doxygen-1.9.8.linux.bin.tar.gz
        sudo cp doxygen-1.9.8/bin/* /usr/bin
    - name: Download and Install PlantUML
      run: |
        wget https://github.com/plantuml/plantuml/releases/download/v1.2023.11/plantuml-1.2023.11.jar
        mkdir -p /usr/share/plantuml
        sudo cp plantuml-1.2023.11.jar /usr/share/plantuml/plantuml.jar
    - name: checkout
      uses: actions/checkout@v4
    - name: build docs
      run: |
        cmake --preset github-ci-debug
        cmake --build --preset github-ci-debug --target docs
      env:
        PLANTUML_JAR: "/usr/share/plantuml/plantuml.jar"
    - name: deploy docs
      uses: JamesIves/github-pages-deploy-action@v4
      with:
          folder: build-github-ci-debug/docs/html
