# SPDX-FileCopyrightText: 2023 Florian Weßel <florianwessel@gmx.net>
#
# SPDX-License-Identifier: GPL-2.0-or-later
name: Blabby Pull Request CI

on:
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Install Qt
      uses: jurplel/install-qt-action@v3
      with:
        version: '5.15.2'
        cache: 'true'
    - name: Install Clang-Tidy
      run: |
        sudo apt update && sudo apt install clang-tidy-14
    - name: checkout
      uses: actions/checkout@v4
      with:
          fetch-depth: 0
    - name: build and test
      run: |
        for commit in $(git rev-list --reverse origin/${{ github.base_ref }}..origin/${{ github.head_ref }}); do
          echo "###############################################################"
          echo "# Start Build Commit $commit"
          echo "###############################################################"
          git checkout $commit
          cmake --preset github-ci-debug
          cmake --build --preset github-ci-debug -- -j
          ctest --preset github-test
          echo "###############################################################"
          echo "# Finished Build Commit $commit"
          echo "###############################################################"
        done
      env:
        QT_QPA_PLATFORM: offscreen
    - name: Static Code Analysis
      run: |
        files=$(git diff --name-status --dirstat=files origin/${{ github.base_ref }}..origin/${{ github.head_ref }} | awk -F'\t' '{ print $2}'| grep -e ".*.h$" -e ".*.hpp$" -e ".*.cpp$") || true
        if [[ ! -z ${files} ]]; then
          clang-tidy -p build-github-ci-debug --export-fixes=clang-tidy-fixes.yml ${files}
        else
          echo "No file for checking create empty fix file."
          touch clang-tidy-fixes.yml
        fi
    - name: Publish Static Code Results
      uses: platisd/clang-tidy-pr-comments@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        clang_tidy_fixes: clang-tidy-fixes.yml
    - name: Check Clang-Tidy Warnings
      run: |
        if [ -e clang-tidy-fixes.yml ]; then
          filesize=$(stat -c '%s' clang-tidy-fixes.yml)
          if [ $filesize -gt 0 ]; then
            echo "clang-tidy warnings found."
            exit 1
          else
            exit 0
          fi
        fi
