# SPDX-FileCopyrightText: 2023 Florian Weßel <florianwessel@gmx.net>
#
# SPDX-License-Identifier: GPL-2.0-or-later
name: Blabby Pull Request CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Install Qt
      uses: jurplel/install-qt-action@v3
      with:
        version: '5.15.2'
    - name: checkout
      uses: actions/checkout@v2
      with:
          fetch-depth: 0
    - name: build and test
      run: |
        for commit in $(git rev-list origin/${{ github.base_ref }}..origin/${{ github.head_ref }}); do
          echo "###############################################################"
          echo "# Start Build Commit $commit"
          echo "###############################################################"
          git checkout $commit
          cmake --preset github-ci-debug
          cmake --build --preset github-ci-debug -- -j
          ctest --preset github-test
          echo "###############################################################"
          echo "# Finished Build Commit $commit"
          echo "###############################################################"
        done
      env:
        QT_QPA_PLATFORM: offscreen
